services:
  client:
    build:
      context: ./client/front/.
      dockerfile: Dockerfile
    container_name: client
    ports:
      - 3000:3000
    restart: "on-failure"
    volumes:
      - './client/front:/app'
      - '/app/node_modules'
    stdin_open: true
    tty: true

  back:
    container_name: back
    build:
      context: ./server/back/.
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    volumes:
      - './server/back:/app'
